# Generated by Django 6.0 on 2025-12-25 07:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Provider-specific message ID', max_length=255)),
                ('thread_id', models.CharField(blank=True, help_text='Thread/conversation ID', max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('from_address', models.EmailField(max_length=254)),
                ('to_addresses', models.TextField(help_text='JSON list of recipient addresses')),
                ('cc_addresses', models.TextField(blank=True, help_text='JSON list of CC addresses')),
                ('bcc_addresses', models.TextField(blank=True, help_text='JSON list of BCC addresses')),
                ('snippet', models.TextField(blank=True, help_text='Short preview of message content')),
                ('body_plain', models.TextField(blank=True, help_text='Plain text body')),
                ('body_html', models.TextField(blank=True, help_text='HTML body')),
                ('sent_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('size', models.IntegerField(help_text='Message size in bytes')),
                ('labels', models.TextField(blank=True, help_text='JSON list of labels/tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.IntegerField(help_text='Attachment size in bytes')),
                ('attachment_id', models.CharField(help_text='Provider-specific attachment ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sync.emailmessage')),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('folder', 'Folder Sync')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('messages_processed', models.IntegerField(default=0)),
                ('messages_added', models.IntegerField(default=0)),
                ('messages_updated', models.IntegerField(default=0)),
                ('messages_deleted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_syncing', models.BooleanField(default=False)),
                ('last_sync_started', models.DateTimeField(blank=True, null=True)),
                ('last_sync_completed', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('synced_messages', models.IntegerField(default=0)),
                ('sync_from_date', models.DateTimeField(blank=True, help_text='Sync messages from this date', null=True)),
                ('sync_to_date', models.DateTimeField(blank=True, help_text='Sync messages up to this date', null=True)),
                ('provider_folder', models.CharField(blank=True, help_text='Folder/label being synced', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emails.emailaccount')),
            ],
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['user', 'received_at'], name='sync_emailm_user_id_e2fc78_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['user', 'is_read'], name='sync_emailm_user_id_1f0802_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['user', 'is_spam'], name='sync_emailm_user_id_f36a05_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['email_account', 'received_at'], name='sync_emailm_email_a_2b6e37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together={('email_account', 'message_id')},
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['email_account', '-started_at'], name='sync_synclo_email_a_c29a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['status'], name='sync_synclo_status_bff9a9_idx'),
        ),
    ]
