# Generated by Django 6.0 on 2025-12-25 07:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='oauthconnection',
            name='unique_user_provider',
        ),
        migrations.AlterUniqueTogether(
            name='oauthconnection',
            unique_together={('user', 'provider')},
        ),
    ]
